---
kind: Template
apiVersion: v1
metadata:
  name: django-psql-persistent
  annotations:
    openshift.io/display-name: Django + PostgreSQL
    description: An example Django application with a PostgreSQL database. For more
      information about using this template, including OpenShift considerations, see
      https://github.com/sclorg/django-ex/blob/master/README.md.
    tags: quickstart,python,django
    iconClass: icon-python
    openshift.io/long-description: This template defines resources needed to develop
      a Django based application, including a build configuration, application deployment
      configuration, and database deployment configuration.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://github.com/sclorg/django-ex
    openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: 'false'
labels:
  template: django-psql-persistent
  app: django-psql-persistent
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: BuildConfig for sample django application
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: "${NAMESPACE}"
          name: python:${PYTHON_VERSION}
        env:
        - name: PIP_INDEX_URL
          value: "${PIP_INDEX_URL}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    postCommit:
      script: "./manage.py test"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: django-psql-persistent
- name: NAMESPACE
  displayName: Namespace
  required: true
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
- name: PYTHON_VERSION
  displayName: Version of Python Image
  description: Version of Python image to be used (3.6 or latest).
  value: '3.6'
  required: true
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  required: true
  description: The URL of the repository with your application source code.
  value: https://github.com/raijin-hq/django-ex.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  required: true
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  value: pipeline-practice
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root of your repository.
- name: PIP_INDEX_URL
  displayName: Custom PyPi Index URL
  description: The custom PyPi index URL
  value: ''
